class_name Sfx
extends Node
## Sound effects channel rack. Loads the WAVs generated by tools/gen_sfx.py
## from res://assets/sfx/ and plays them on dedicated AudioStreamPlayers
## (small pools for kick/bounce so rapid hits can overlap).
## Self-contained: main.gd adds this node and calls the play_* API.

const SFX_DIR := "res://assets/sfx/"
const CROWD_DB := -16.0          # modest crowd bed level
const CHEER_DB := -5.0
const WHISTLE_DB := -8.0
const KICK_POOL_SIZE := 3
const BOUNCE_POOL_SIZE := 2

var _kick_stream: AudioStream
var _bounce_stream: AudioStream
var _cheer_stream: AudioStream
var _crowd_stream: AudioStream
var _whistle_streams: Array[AudioStream] = []

var _kick_pool: Array[AudioStreamPlayer] = []
var _bounce_pool: Array[AudioStreamPlayer] = []
var _whistle_player: AudioStreamPlayer
var _cheer_player: AudioStreamPlayer
var _crowd_player: AudioStreamPlayer
var _kick_i := 0
var _bounce_i := 0
var _crowd_tween: Tween


func _ready() -> void:
	name = "Sfx"
	_kick_stream = _load_stream("kick.wav")
	_bounce_stream = _load_stream("bounce.wav")
	_cheer_stream = _load_stream("cheer.wav")
	_crowd_stream = _load_stream("crowd.wav")
	_whistle_streams = [
		_load_stream("whistle.wav"),       # 0: single short blast
		_load_stream("whistle2.wav"),      # 1: double blast
		_load_stream("whistle_long.wav"),  # 2: long blast
	]
	for i in KICK_POOL_SIZE:
		_kick_pool.append(_make_player("Kick%d" % i))
	for i in BOUNCE_POOL_SIZE:
		_bounce_pool.append(_make_player("Bounce%d" % i))
	_whistle_player = _make_player("Whistle")
	_cheer_player = _make_player("Cheer")
	_crowd_player = _make_player("Crowd")
	_make_loopable(_crowd_stream)


## strength 0..1 — pass taps quiet/bright, full shots loud/deep.
func play_kick(strength: float) -> void:
	if _kick_stream == null:
		return
	var s := clampf(strength, 0.0, 1.0)
	var p := _kick_pool[_kick_i]
	_kick_i = (_kick_i + 1) % _kick_pool.size()
	p.stream = _kick_stream
	p.volume_db = lerpf(-15.0, -3.0, s)
	p.pitch_scale = lerpf(1.12, 0.9, s) * randf_range(0.96, 1.04)
	p.play()


## kind: 0 = single, 1 = double, 2 = long.
func play_whistle(kind: int) -> void:
	var i := clampi(kind, 0, _whistle_streams.size() - 1)
	var stream := _whistle_streams[i]
	if stream == null or _whistle_player == null:
		return
	_whistle_player.stream = stream
	_whistle_player.volume_db = WHISTLE_DB
	_whistle_player.pitch_scale = randf_range(0.99, 1.01)
	_whistle_player.play()


func play_cheer() -> void:
	if _cheer_stream != null and _cheer_player != null:
		_cheer_player.stream = _cheer_stream
		_cheer_player.volume_db = CHEER_DB
		_cheer_player.pitch_scale = randf_range(0.97, 1.03)
		_cheer_player.play()
	# Lift the crowd bed under the roar, then settle back down.
	if _crowd_player != null and _crowd_player.playing:
		if _crowd_tween != null and _crowd_tween.is_valid():
			_crowd_tween.kill()
		_crowd_tween = create_tween()
		_crowd_tween.tween_property(_crowd_player, "volume_db", CROWD_DB + 7.0, 0.35)
		_crowd_tween.tween_interval(1.8)
		_crowd_tween.tween_property(_crowd_player, "volume_db", CROWD_DB, 2.6)


## strength 0..1 scaled from impact speed; micro-bounces are skipped.
func play_bounce(strength: float) -> void:
	if _bounce_stream == null:
		return
	var s := clampf(strength, 0.0, 1.0)
	if s < 0.04:
		return
	var p := _bounce_pool[_bounce_i]
	_bounce_i = (_bounce_i + 1) % _bounce_pool.size()
	p.stream = _bounce_stream
	p.volume_db = lerpf(-26.0, -8.0, s)
	p.pitch_scale = lerpf(1.15, 0.92, s) * randf_range(0.95, 1.05)
	p.play()


## Starts the looping stadium ambience (idempotent).
func start_crowd() -> void:
	if _crowd_stream == null or _crowd_player == null or _crowd_player.playing:
		return
	_crowd_player.stream = _crowd_stream
	_crowd_player.volume_db = CROWD_DB
	_crowd_player.pitch_scale = 1.0
	_crowd_player.play()


# --- Internals ---------------------------------------------------------------

func _make_player(pname: String) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.name = pname
	p.bus = "Master"
	add_child(p)
	return p


func _load_stream(fname: String) -> AudioStream:
	var path := SFX_DIR + fname
	if ResourceLoader.exists(path):
		var res: Resource = load(path)
		if res is AudioStream:
			return res
	push_warning("Sfx: could not load " + path)
	return null


func _make_loopable(stream: AudioStream) -> void:
	var ws := stream as AudioStreamWAV
	if ws == null:
		return
	ws.loop_mode = AudioStreamWAV.LOOP_FORWARD
	ws.loop_begin = 0
	ws.loop_end = ws.data.size() / 2  # 16-bit mono: 2 bytes per frame
